### ISSUE TITLE
Simplify SessionStorage code

### ISSUE THREAD

**Issue by dhuangg** [ScandinavianSection-UCLA/Nexus2#92]
Session Storage code is poorly written - each data for session storage is manually stored per line of session storage. 

**Tasks**
- [ ] Create inventory of storage containers that need to be created (i.e. Navigation, tabs, usernexus, etc.) 
- [ ] Create big session storage containers in model (i.e. NavigationSessionStorage)
- [ ] Create functions to set NavigationSessionStorage in a new session storage model. This should also set session storage.
- [ ] Create functions to retrieve NavigationSessionStorage in new session storage model

Example: 
```
/*Save items to local storage for data to continue to exist after tab switch/page refresh  */
sessionStorage.setItem('lists', JSON.stringify(this.state['lists']));
sessionStorage.setItem('itemsList', JSON.stringify(items));
sessionStorage.setItem('displayOntology', JSON.stringify(ontology));
sessionStorage.setItem('lastIDKey', JSON.stringify(idKey));
sessionStorage.setItem('lastDisplayKey',JSON.stringify(displayKey));
```
Instead, we can place all of these strings and arrays into a `NavigationSessionStorage` object
```
const NavigationSessionStorage = 
{
    lists: GeneratedList,
    itemsList: GeneratedItemsList,
    displayOntology: SavedDisplayOntology,
    etc.
}
sessionStorage.setItem('NavigationSessionStorage', JSON.stringify(NavigationSessionStorage));
```

We also need to change how it's retrieved. So instead of this: 
```
const lists = sessionStorage.getItem('lists');
const itemsList = sessionStorage.getItem('itemsList');
const lastIDKey = JSON.parse(sessionStorage.getItem('lastIDKey'));
const lastDisplayKey = JSON.parse(sessionStorage.getItem('lastDisplayKey'));
```

We can retrieve it like:
```
const NavigationSessionStorage = JSON.parse(sessionStorage.getItem('NavigationSessionStorage'));
```
